import { Roboto } from 'next/font/google';
import './globals.css';
import { icons } from 'lucide-react';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata = {
  title: 'NKB - Buxgalteriya xizmatlari',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/nkb.svg" type="image/svg+xml" />
      </head>
      <body className={`${roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}